-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2021-01-14 09:00:20.281

-- tables
-- Table: AREA
CREATE TABLE AREA (
    CODARE serial  NOT NULL,
    NOMARE varchar(30)  NOT NULL,
    ESTARE char(1)  NOT NULL,
    CONSTRAINT AREA_pk PRIMARY KEY (CODARE)
);

-- Table: ASIGNACION
CREATE TABLE ASIGNACION (
    IDASIG serial  NOT NULL,
    IDAUL int  NOT NULL,
    IDTRA int  NOT NULL,
    CODARE int  NOT NULL,
    ESTASIG char(1)  NOT NULL,
    CONSTRAINT ASIGNACION_pk PRIMARY KEY (IDASIG)
);

-- Table: ASISTENCIA
CREATE TABLE ASISTENCIA (
    CODAS serial  NOT NULL,
    TIPASIS char(1)  NOT NULL,
    ESTASIS char(1)  NOT NULL,
    FECHASIS timestamp  NOT NULL,
    JUSTASIS varchar(150)  NOT NULL,
    IDASIG int  NOT NULL,
    CODMAT int  NOT NULL,
    CONSTRAINT ASISTENCIA_pk PRIMARY KEY (CODAS)
);

-- Table: AULA
CREATE TABLE AULA (
    IDAUL serial  NOT NULL,
    IDCOL int  NOT NULL,
    GRAAUL varchar(25)  NOT NULL,
    SECAUL varchar(25)  NOT NULL,
    ALIAUL varchar(25)  NOT NULL,
    CANTAUL int  NOT NULL,
    ESTAUL char(1)  NOT NULL,
    CONSTRAINT AULA_pk PRIMARY KEY (IDAUL)
);

-- Table: CALIFICACION
CREATE TABLE CALIFICACION (
    IDCAL serial  NOT NULL,
    IDASIG serial  NOT NULL,
    IDCRITCUR serial  NOT NULL,
    CODMAT serial  NOT NULL,
    NOTCAL_ORDCAL numeric  NOT NULL,
    NOTCAL_LITCAL varchar(2)  NOT NULL,
    PESCAL numeric  NOT NULL,
    FECCAL date  NOT NULL,
    CONDESCAL varchar(100)  NULL,
    CONSTRAINT CALIFICACION_pk PRIMARY KEY (IDCAL)
);

-- Table: COLEGIO
CREATE TABLE COLEGIO (
    IDCOL serial  NOT NULL,
    DIRCOL varchar(100)  NOT NULL,
    NOMCOL varchar(100)  NOT NULL,
    FRECREP char(1)  NOT NULL,
    INSIGCOL varchar(120)  NOT NULL,
    NUMUG int  NOT NULL,
    ESTCOL char(1)  NOT NULL,
    CONSTRAINT COLEGIO_pk PRIMARY KEY (IDCOL)
);

-- Table: COMPETENCIA
CREATE TABLE COMPETENCIA (
    IDCOM serial  NOT NULL,
    NOMCOM varchar(50)  NOT NULL,
    ESTCOM char(1)  NOT NULL,
    CONSTRAINT COMPETENCIA_pk PRIMARY KEY (IDCOM)
);

-- Table: CRITERIO
CREATE TABLE CRITERIO (
    CODCRIT serial  NOT NULL,
    NOMCRIT varchar(50)  NOT NULL,
    IDCOM int  NOT NULL,
    ESTCRIT char(1)  NOT NULL,
    DESCRIT varchar(200)  NOT NULL,
    CONSTRAINT CRITERIO_pk PRIMARY KEY (CODCRIT)
);

-- Table: CRITERIO_CURSO
CREATE TABLE CRITERIO_CURSO (
    IDCRITCUR serial  NOT NULL,
    CODCRIT serial  NOT NULL,
    ESTCRIT char(1)  NOT NULL,
    CONSTRAINT CRITERIO_CURSO_pk PRIMARY KEY (IDCRITCUR)
);

-- Table: MATRICULA
CREATE TABLE MATRICULA (
    CODMAT serial  NOT NULL,
    PERIDLEC int  NOT NULL,
    IDTRADIR int  NOT NULL,
    IDUSUAPO int  NOT NULL,
    IDUSUESTMAT int  NOT NULL,
    AULA_IDAUL int  NOT NULL,
    FECMAT timestamp  NOT NULL,
    FECCULMAT timestamp  NOT NULL,
    CALMODMAT char(1)  NOT NULL,
    ISEXPORTED boolean  NULL DEFAULT false,
    ESTMAT char(1)  NOT NULL,
    CONSTRAINT MATRICULA_pk PRIMARY KEY (CODMAT)
);

-- Table: PERIODO_LECTIVO
CREATE TABLE PERIODO_LECTIVO (
    PERIDLEC serial  NOT NULL,
    NOMPERLEC varchar(50)  NOT NULL,
    ANIOPERLEC varchar(4)  NOT NULL,
    DIVPERLEC int  NOT NULL,
    CONSTRAINT PERIODO_LECTIVO_pk PRIMARY KEY (PERIDLEC)
);

-- Table: PERSONA
CREATE TABLE PERSONA (
    IDPER serial  NOT NULL,
    DNIPER char(8)  NOT NULL,
    NOMPER varchar(70)  NOT NULL,
    APEPATPER varchar(70)  NOT NULL,
    APEMATPER varchar(70)  NOT NULL,
    SEXPER char(1)  NOT NULL,
    ESTPER char(1)  NOT NULL,
    DIRPER varchar(100)  NOT NULL,
    CELPER char(9)  NOT NULL,
    EMAILPER varchar(100)  NOT NULL,
    ANIONACPER date  NOT NULL,
    CODUBI varchar(50)  NOT NULL,
    CONSTRAINT PERSONA_pk PRIMARY KEY (IDPER)
);

-- Table: TRABAJADOR
CREATE TABLE TRABAJADOR (
    IDTRA serial  NOT NULL,
    IDUSU int  NOT NULL,
    IDCOL int  NOT NULL,
    FECHINTRA timestamp  NOT NULL,
    FECHFINTRA timestamp  NOT NULL,
    ESTTRA char(1)  NOT NULL,
    CONSTRAINT TRABAJADOR_pk PRIMARY KEY (IDTRA)
);

-- Table: UBIGEO
CREATE TABLE UBIGEO (
    CODUBI varchar(50)  NOT NULL,
    DEPUBI varchar(50)  NOT NULL,
    PROVUBI varchar(50)  NOT NULL,
    DISTUBI varchar(50)  NOT NULL,
    CONSTRAINT UBIGEO_pk PRIMARY KEY (CODUBI)
);

-- Table: USUARIO
CREATE TABLE USUARIO (
    IDUSU serial  NOT NULL,
    IDPER int  NOT NULL,
    ROLUSU char(1)  NOT NULL,
    USUUSU varchar(50)  NOT NULL,
    PSWUSU varchar(50)  NOT NULL,
    ESTUSU char(1)  NOT NULL,
    CONSTRAINT USUARIO_pk PRIMARY KEY (IDUSU)
);

-- foreign keys
-- Reference: AREA_AULA_IDAUL (table: ASIGNACION)
ALTER TABLE ASIGNACION ADD CONSTRAINT AREA_AULA_IDAUL
    FOREIGN KEY (IDAUL)
    REFERENCES AULA (IDAUL)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: ASIGNACION_AREA_CODARE (table: ASIGNACION)
ALTER TABLE ASIGNACION ADD CONSTRAINT ASIGNACION_AREA_CODARE
    FOREIGN KEY (CODARE)
    REFERENCES AREA (CODARE)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: ASIGNACION_TRABAJADOR_IDTRA (table: ASIGNACION)
ALTER TABLE ASIGNACION ADD CONSTRAINT ASIGNACION_TRABAJADOR_IDTRA
    FOREIGN KEY (IDTRA)
    REFERENCES TRABAJADOR (IDTRA)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: ASISTENCIA_ASIGNACION_IDASIG (table: ASISTENCIA)
ALTER TABLE ASISTENCIA ADD CONSTRAINT ASISTENCIA_ASIGNACION_IDASIG
    FOREIGN KEY (IDASIG)
    REFERENCES ASIGNACION (IDASIG)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: ASISTENCIA_MATRICULA_CODMAT (table: ASISTENCIA)
ALTER TABLE ASISTENCIA ADD CONSTRAINT ASISTENCIA_MATRICULA_CODMAT
    FOREIGN KEY (CODMAT)
    REFERENCES MATRICULA (CODMAT)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: AULA_COLEGIO_IDCOL (table: AULA)
ALTER TABLE AULA ADD CONSTRAINT AULA_COLEGIO_IDCOL
    FOREIGN KEY (IDCOL)
    REFERENCES COLEGIO (IDCOL)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CALIFICACION_ASIGNACION_IDASIG (table: CALIFICACION)
ALTER TABLE CALIFICACION ADD CONSTRAINT CALIFICACION_ASIGNACION_IDASIG
    FOREIGN KEY (IDASIG)
    REFERENCES ASIGNACION (IDASIG)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CALIFICACION_CRITERIO_CURSO_CODCRIT (table: CALIFICACION)
ALTER TABLE CALIFICACION ADD CONSTRAINT CALIFICACION_CRITERIO_CURSO_CODCRIT
    FOREIGN KEY (IDCRITCUR)
    REFERENCES CRITERIO_CURSO (IDCRITCUR)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CALIFICACION_MATRICULA_CODMAT (table: CALIFICACION)
ALTER TABLE CALIFICACION ADD CONSTRAINT CALIFICACION_MATRICULA_CODMAT
    FOREIGN KEY (CODMAT)
    REFERENCES MATRICULA (CODMAT)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CRITERIO_COMPETENCIA (table: CRITERIO)
ALTER TABLE CRITERIO ADD CONSTRAINT CRITERIO_COMPETENCIA
    FOREIGN KEY (IDCOM)
    REFERENCES COMPETENCIA (IDCOM)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: CRITERIO_CURSO_CRITERIO (table: CRITERIO_CURSO)
ALTER TABLE CRITERIO_CURSO ADD CONSTRAINT CRITERIO_CURSO_CRITERIO
    FOREIGN KEY (CODCRIT)
    REFERENCES CRITERIO (CODCRIT)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MATRICULA_AULA (table: MATRICULA)
ALTER TABLE MATRICULA ADD CONSTRAINT MATRICULA_AULA
    FOREIGN KEY (AULA_IDAUL)
    REFERENCES AULA (IDAUL)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MATRICULA_PERIODO_LECTIVO (table: MATRICULA)
ALTER TABLE MATRICULA ADD CONSTRAINT MATRICULA_PERIODO_LECTIVO
    FOREIGN KEY (PERIDLEC)
    REFERENCES PERIODO_LECTIVO (PERIDLEC)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MATRICULA_TRABAJADOR_IDTRA (table: MATRICULA)
ALTER TABLE MATRICULA ADD CONSTRAINT MATRICULA_TRABAJADOR_IDTRA
    FOREIGN KEY (IDTRADIR)
    REFERENCES TRABAJADOR (IDTRA)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MATRICULA_USUARIO (table: MATRICULA)
ALTER TABLE MATRICULA ADD CONSTRAINT MATRICULA_USUARIO
    FOREIGN KEY (IDUSUESTMAT)
    REFERENCES USUARIO (IDUSU)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: MATRICULA_USUARIO_IDUSU (table: MATRICULA)
ALTER TABLE MATRICULA ADD CONSTRAINT MATRICULA_USUARIO_IDUSU
    FOREIGN KEY (IDUSUAPO)
    REFERENCES USUARIO (IDUSU)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: PERSONA_UBIGEO_IDUBI (table: PERSONA)
ALTER TABLE PERSONA ADD CONSTRAINT PERSONA_UBIGEO_IDUBI
    FOREIGN KEY (CODUBI)
    REFERENCES UBIGEO (CODUBI)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: TRABAJADOR_COLEGIO_IDCOL (table: TRABAJADOR)
ALTER TABLE TRABAJADOR ADD CONSTRAINT TRABAJADOR_COLEGIO_IDCOL
    FOREIGN KEY (IDCOL)
    REFERENCES COLEGIO (IDCOL)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: TRABAJADOR_USUARIO_IDUSU (table: TRABAJADOR)
ALTER TABLE TRABAJADOR ADD CONSTRAINT TRABAJADOR_USUARIO_IDUSU
    FOREIGN KEY (IDUSU)
    REFERENCES USUARIO (IDUSU)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: USUARIO_PERSONA_IDPER (table: USUARIO)
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PERSONA_IDPER
    FOREIGN KEY (IDPER)
    REFERENCES PERSONA (IDPER)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

