version: "3.8"
services:
  postgre-db:
    image: "postgres:10-alpine"
    container_name: "sadeb-db"
    volumes:
      - ./sql_files:/docker-entrypoint-initdb.d
    env_file:
      - dev.env
    ports:
      - "5432:5432"

  sadeb-backend:
    build: .
    container_name: "sadeb-be"
    env_file:
      - dev.env
    ports:
      - "8080:8080"
    depends_on:
      - postgre-db