GET http://localhost:8080/ubigeo
Accept: application/json

###
POST http://localhost:8080/ubigeo
Content-Type: application/json

{
  "codigo": "codigo123",
  "departamento": "lima",
  "provincia": "lima prov",
  "distrito": "cañete"
}

###
